/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'owner' : IDL.Principal,
  'reminderTime' : IDL.Opt(Time),
});
export const Assignment = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'dueDate' : IDL.Opt(Time),
  'taskId' : IDL.Nat,
  'subjectId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StudySubject = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'assignments' : IDL.Vec(Assignment),
  'owner' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAssignment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(Time)],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'addTask' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearTaskReminder' : IDL.Func([IDL.Nat], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'createSubject' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteAssignment' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAssignments' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(Assignment))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyGoal' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Nat)], ['query']),
  'getProgressPercentage' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(StudySubject)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDailyGoal' : IDL.Func([IDL.Nat], [], []),
  'setTaskReminder' : IDL.Func([IDL.Nat, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'owner' : IDL.Principal,
    'reminderTime' : IDL.Opt(Time),
  });
  const Assignment = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'dueDate' : IDL.Opt(Time),
    'taskId' : IDL.Nat,
    'subjectId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StudySubject = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'assignments' : IDL.Vec(Assignment),
    'owner' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAssignment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(Time)],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'addTask' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearTaskReminder' : IDL.Func([IDL.Nat], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'createSubject' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteAssignment' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAssignments' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(Assignment))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyGoal' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Nat)], ['query']),
    'getProgressPercentage' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(StudySubject)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDailyGoal' : IDL.Func([IDL.Nat], [], []),
    'setTaskReminder' : IDL.Func([IDL.Nat, Time], [], []),
  });
};

export const init = ({ IDL }) => { return []; };